### ISSUE TITLE
Some pages cannot be rendered fully

### ISSUE THREAD

**Issue by j12358962** [iAgentNTU/iAgentNTU.github.io#72]
Some pages cannot be rendered fully. I guess the reason is **bib**. 
These profile are including `bibsrc: '#bibtex'` but no `<pre id="bibtex">` provided. 

For example:
https://iagentntu.github.io/people/images/Yu-Huan_Huang.html
https://iagentntu.github.io/people/Chia-Wen_Yeh.html
https://iagentntu.github.io/people/Yi-Ning_Chen.html

Solution:
Comment or remove `bibsrc: '#bibtex'` line

**Comment by erickchandra1** [comment]
@j12358962 Thanks for raising the bug issue. Fixed: @emschenn
